name: Test & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run test:unit:ci
      - name: Upload coverage Reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-coverage
          retention-days: 3
          path: |
            reports/unit/coverage/cobertura-coverage.xml

      - name: Upload coverage Reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          retention-days: 3
          path: |
            reports/unit/results/results.xml
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build